[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self' https://cdnjs.cloudflare.com https://fonts.googleapis.com https://fonts.gstatic.com https://discord.gg https://randomuser.me; img-src 'self' data: https://*; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdnjs.cloudflare.com; script-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
